#ifndef __MACH_GPIO_P11_H
#define __MACH_GPIO_P11 __FILE__

#include <mach/gpio.h>

extern void p11_config_gpio_table(void);
extern void p11_config_sleep_gpio_table(void);

#define	GPIO_5M_CAM_SCL_18V	EXYNOS5_GPF0(1)
#define	GPIO_5M_CAM_SDA_18V	EXYNOS5_GPF0(0)
#define	GPIO_5M_CORE_EN		EXYNOS5_GPY6(2)
#define	GPIO_5M_nRST		EXYNOS5_GPY3(7)
#define	GPIO_5M_SPI_CLK		EXYNOS5_GPA2(4)
#define	GPIO_5M_SPI_CS		EXYNOS5_GPA2(5)
#define	GPIO_5M_SPI_DI		EXYNOS5_GPA2(6)
#define	GPIO_5M_SPI_DO		EXYNOS5_GPA2(7)

#define	GPIO_ACC_INT		EXYNOS5_GPX1(4)

#define	GPIO_ACCESSORY_EN	EXYNOS5_GPH1(5)
#define	GPIO_ACCESSORY_INT	EXYNOS5_GPX3(2)

#define	GPIO_ADC_INT		EXYNOS5_GPX2(4)
#define	GPIO_ADC_SCL_18V	EXYNOS5_GPY2(3)
#define	GPIO_ADC_SDA_18V	EXYNOS5_GPY2(2)

#define	GPIO_AMP_L_INT		EXYNOS5_GPB0(1)
#define	GPIO_AMP_L_SCL_18V	EXYNOS5_GPC1(1)
#define	GPIO_AMP_L_SDA_18V	EXYNOS5_GPC1(0)
#define	GPIO_AMP_R_INT		EXYNOS5_GPB1(0)
#define	GPIO_AMP_R_SCL_18V	EXYNOS5_GPB1(2)
#define	GPIO_AMP_R_SDA_18V	EXYNOS5_GPB1(1)

#define	GPIO_BARO_INT		EXYNOS5_GPX0(3)

#define	GPIO_BSENSE_SCL_18V	EXYNOS5_GPD0(3)
#define	GPIO_BSENSE_SDA_18V	EXYNOS5_GPD0(2)

#define	GPIO_BT_CTS		EXYNOS5_GPA0(2)
#define	GPIO_BT_CTS_AF		2
#define	GPIO_BT_EN		EXYNOS5_GPY4(1)
#define	GPIO_BT_HOST_WAKE	EXYNOS5_GPX2(6)
#define	GPIO_BT_nRST		EXYNOS5_GPY4(0)
#define	GPIO_BT_RTS		EXYNOS5_GPA0(3)
#define	GPIO_BT_RTS_AF		2
#define	GPIO_BT_RXD		EXYNOS5_GPA0(0)
#define	GPIO_BT_RXD_AF		2
#define	GPIO_BT_TXD		EXYNOS5_GPA0(1)
#define	GPIO_BT_TXD_AF		2
#define	GPIO_BT_WAKE		EXYNOS5_GPH1(3)

#define	GPIO_BUCK2_SEL		EXYNOS5_GPY6(0)
#define	GPIO_BUCK3_SEL		EXYNOS5_GPY6(3)
#define	GPIO_BUCK4_SEL		EXYNOS5_GPY6(4)

#define	GPIO_C2C_DETECT_18V	EXYNOS5_GPY6(5)

#define	GPIO_CAM_IO_EN		EXYNOS5_GPY6(1)
#define	GPIO_CAM_MCLK		EXYNOS5_GPH0(3)
#define	GPIO_CAM_VT_nRST	EXYNOS5_GPG1(6)

#define	GPIO_CHG_SCL_18V	EXYNOS5_GPA2(1)
#define	GPIO_CHG_SDA_18V	EXYNOS5_GPA2(0)

#define	GPIO_CMC_CLK_18V	EXYNOS5_GPF1(0)
#define	GPIO_CMC_CS_18V		EXYNOS5_GPF1(1)
#define	GPIO_CODEC_LDO_EN	EXYNOS5_GPH1(1)
#define	GPIO_CODEC_SCL_18V	EXYNOS5_GPB2(3)
#define	GPIO_CODEC_SDA_18V	EXYNOS5_GPB2(2)

#define	GPIO_CP_DUMP_INT	EXYNOS5_GPX1(2)
#define	GPIO_CP_ON		EXYNOS5_GPD1(5)

#define	GPIO_DET_35		EXYNOS5_GPX0(1)

#define	GPIO_DOCK_INT		EXYNOS5_GPX3(0)

#define	GPIO_DP_HPD		EXYNOS5_GPX0(7)

#define	GPIO_EAR_SEND_END	EXYNOS5_GPX3(6)

#define	GPIO_eMMC_EN		EXYNOS5_GPC0(2)

#define	GPIO_FLM_RXD		EXYNOS5_GPA1(4)
#define	GPIO_FLM_RXD_AF		2
#define	GPIO_FLM_TXD		EXYNOS5_GPA1(5)
#define	GPIO_FLM_TXD_AF		2

#define	GPIO_FUEL_ALERT		EXYNOS5_GPX2(3)
#define	GPIO_FUEL_SCL_18V	EXYNOS5_GPD0(1)
#define	GPIO_FUEL_SDA_18V	EXYNOS5_GPD0(0)

#define	GPIO_GPS_CNTL		EXYNOS5_GPY3(6)
#define	GPIO_GPS_CTS		EXYNOS5_GPA0(6)
#define	GPIO_GPS_CTS_AF		2
#define	GPIO_GPS_EN		EXYNOS5_GPY6(7)
#define	GPIO_GPS_nRST		EXYNOS5_GPY6(6)
#define	GPIO_GPS_RTS		EXYNOS5_GPA0(7)
#define	GPIO_GPS_RTS_AF		2
#define	GPIO_GPS_RXD		EXYNOS5_GPA0(4)
#define	GPIO_GPS_RXD_AF		2
#define	GPIO_GPS_TXD		EXYNOS5_GPA0(5)
#define	GPIO_GPS_TXD_AF		2

#define	GPIO_GSENSE_SCL_18V	EXYNOS5_GPB3(3)
#define	GPIO_GSENSE_SDA_18V	EXYNOS5_GPB3(2)

#define	GPIO_HDMI_CEC		EXYNOS5_GPX3(6)
#define	GPIO_HDMI_EN		EXYNOS5_GPY3(2)
#define	GPIO_HDMI_HPD		EXYNOS5_GPX3(7)

#define	GPIO_HUM_SCL_18V	EXYNOS5_GPY3(1)
#define	GPIO_HUM_SDA_18V	EXYNOS5_GPY3(0)

#define	GPIO_HW_REV0		EXYNOS5_GPY5(0)
#define	GPIO_HW_REV1		EXYNOS5_GPY5(1)
#define	GPIO_HW_REV2		EXYNOS5_GPY5(2)
#define	GPIO_HW_REV3		EXYNOS5_GPY5(3)

#define	GPIO_IPC_HOST_WAKEUP	EXYNOS5_GPX1(1)
#define	GPIO_IPC_SLAVE_WAKEUP	EXYNOS5_GPX1(0)

#define	GPIO_IRDA_EN		EXYNOS5_GPH1(7)
#define	GPIO_IRDA_INT_18V	EXYNOS5_GPD1(4)
#define	GPIO_IRDA_nRST_18V	EXYNOS5_GPG0(4)
#define	GPIO_IRDA_SCL_18V	EXYNOS5_GPD0(7)
#define	GPIO_IRDA_SDA_18V	EXYNOS5_GPD0(6)

#define	GPIO_ISP_RXD		EXYNOS5_GPE1(1)
#define	GPIO_ISP_TXD		EXYNOS5_GPE0(7)

#define	GPIO_LCD_APS_EN_18V	EXYNOS5_GPG0(3)
#define	GPIO_LCD_EN		EXYNOS5_GPC2(2)
#define	GPIO_LCD_ID		EXYNOS5_GPY3(4)
#define	GPIO_LCD_PWM_IN_18V	EXYNOS5_GPB2(0)

#define	GPIO_LED_BACKLIGHT_RESET	EXYNOS5_GPG0(5)

#define	GPIO_LIGHT_I2C_SCL	EXYNOS5_GPB1(4)
#define	GPIO_LIGHT_I2C_SDA	EXYNOS5_GPB1(3)
#define	GPIO_LIGHT_nINT		EXYNOS5_GPH1(2)

#define	GPIO_MHL_DSCL_18V	EXYNOS5_GPB3(1)
#define	GPIO_MHL_DSCL_18V	EXYNOS5_GPB3(1)
#define	GPIO_MHL_DSDA_18V	EXYNOS5_GPB3(0)
#define	GPIO_MHL_DSDA_18V	EXYNOS5_GPB3(0)
#define	GPIO_MHL_INT		EXYNOS5_GPG0(6)
#define	GPIO_MHL_RST		EXYNOS5_GPG0(7)
#define	GPIO_MHL_SCL_18V	EXYNOS5_GPD0(5)
#define	GPIO_MHL_SCL_18V	EXYNOS5_GPD0(5)
#define	GPIO_MHL_SDA_18V	EXYNOS5_GPD0(4)
#define	GPIO_MHL_SDA_18V	EXYNOS5_GPD0(4)

#define	GPIO_MOTOR_SCL_18V	EXYNOS5_GPD1(3)
#define	GPIO_MOTOR_SDA_18V	EXYNOS5_GPD1(2)

#define	GPIO_MSENSE_INT		EXYNOS5_GPX2(2)
#define	GPIO_MSENSE_SCL_18V	EXYNOS5_GPY2(5)
#define	GPIO_MSENSE_SDA_18V	EXYNOS5_GPY2(4)

#define	GPIO_nCONNECTED		EXYNOS5_GPX0(0)

#define	GPIO_NFC_EN		EXYNOS5_GPD1(6)
#define	GPIO_NFC_FIRMWARE	EXYNOS5_GPD1(7)
#define	GPIO_NFC_IRQ		EXYNOS5_GPX1(7)
#define	GPIO_NFC_SCL_18V	EXYNOS5_GPY0(0)
#define	GPIO_NFC_SDA_18V	EXYNOS5_GPY0(1)

#define	GPIO_nPOWER		EXYNOS5_GPX2(7)

#define	GPIO_OTG_EN		EXYNOS5_GPY3(3)

#define	GPIO_PDA_ACTIVE		EXYNOS5_GPY4(2)

#define	GPIO_PHONE_ACTIVE	EXYNOS5_GPX1(6)

#define	GPIO_PMIC_DVS1		EXYNOS5_GPY5(5)
#define	GPIO_PMIC_DVS2		EXYNOS5_GPY5(6)
#define	GPIO_PMIC_DVS3		EXYNOS5_GPY5(7)
#define	GPIO_PMIC_IRQ		EXYNOS5_GPX0(2)
#define	GPIO_PMIC_SCL		EXYNOS5_GPA2(3)
#define	GPIO_PMIC_SDA		EXYNOS5_GPA2(2)

#define	GPIO_REC_PCM_CLK	EXYNOS5_GPB0(0)
#define	GPIO_REC_PCM_IN		EXYNOS5_GPB0(3)
#define	GPIO_REC_PCM_OUT	EXYNOS5_GPB0(4)
#define	GPIO_REC_PCM_SYNC	EXYNOS5_GPB0(2)

#define	GPIO_REMOTE_SENSE_IRQ	EXYNOS5_GPX3(1)

#define	GPIO_RESOUT0_N		EXYNOS5_GPX0(5)

#define	GPIO_RESOUT2_N		EXYNOS5_GPX0(6)

#define	GPIO_RGB_SCL_18V	EXYNOS5_GPD1(1)
#define	GPIO_RGB_SDA_18V	EXYNOS5_GPD1(0)

#define	GPIO_SIM_DETECT		EXYNOS5_GPX3(3)

#define	GPIO_SUSPEND_REQUEST_HSIC	EXYNOS5_GPX1(3)

#define	GPIO_T_FLASH_DETECT	EXYNOS5_GPX3(4)

#define	GPIO_TA_EN		EXYNOS5_GPG1(5)

#define	GPIO_TF_EN		EXYNOS5_GPY0(4)

#define	GPIO_TOUCH_CHG		EXYNOS5_GPG1(2)
#define	GPIO_TOUCH_RESET	EXYNOS5_GPG1(3)

#define	GPIO_TSP_SCL_18V	EXYNOS5_GPA1(3)
#define	GPIO_TSP_SDA_18V	EXYNOS5_GPA1(2)

#define	GPIO_UART_SEL		EXYNOS5_GPY4(7)

#define	GPIO_USB_SEL1		EXYNOS5_GPH0(1)
#define	GPIO_USB_SEL2		EXYNOS5_GPH1(6)

#define	GPIO_USB30_EN		EXYNOS5_GPG0(2)

#define	GPIO_VOL_DOWN		EXYNOS5_GPX2(1)
#define	GPIO_VOL_UP		EXYNOS5_GPX2(0)

#define	GPIO_VT_CAM_SCL_18V	EXYNOS5_GPF0(3)
#define	GPIO_VT_CAM_SDA_18V	EXYNOS5_GPF0(2)

#define	GPIO_WLAN_EN		EXYNOS5_GPH0(0)
#define	GPIO_WLAN_HOST_WAKE	EXYNOS5_GPX2(5)
#define	GPIO_WLAN_SDIO_D0	EXYNOS5_GPC3(3)
#define	GPIO_WLAN_SDIO_D1	EXYNOS5_GPC3(4)
#define	GPIO_WLAN_SDIO_D2	EXYNOS5_GPC3(5)
#define	GPIO_WLAN_SDIO_D3	EXYNOS5_GPC3(6)

#endif /* __MACH_GPIO_P11_H */
