
obj-$(CONFIG_BATTERY_SAMSUNG)	+= samsung_battery.o	\
					battery-factory.o

obj-$(CONFIG_BATTERY_SAMSUNG_S2PLUS)	+= samsung_battery_s2plus.o	\
					battery-factory.o

obj-$(CONFIG_MAX8997_CHARGER)	+= max8997-charger.o

obj-$(CONFIG_BATTERY_MAX17043_FUELGAUGE)	+= max17043_fuelgauge.o
obj-$(CONFIG_BATTERY_MAX17042_FUELGAUGE)	+= max17042_fuelgauge.o
obj-$(CONFIG_BATTERY_MAX17047_FUELGAUGE)	+= max17047_fuelgauge.o

obj-$(CONFIG_BATTERY_SMB136_CHARGER)	+= smb136_charger.o
obj-$(CONFIG_BATTERY_MAX77693_CHARGER)	+= max77693_charger.o
